# Generated by Django 5.0.1 on 2024-02-06 19:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_remove_gym_coordinates_gym_location'),
        ('subscriptions', '0001_initial'),
        ('users', '0003_alter_usersubscription_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('times_used', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfeatures', to='subscriptions.subscriptionfeature')),
                ('gym', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gyms.gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersubscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
