# Generated by Django 5.0.1 on 2024-01-29 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Беларусь', max_length=255)),
                ('city', models.CharField(default='Минск', max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='gym',
            name='name',
            field=models.CharField(default='Базовый план', max_length=255),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(default='Базовая сеть спортзалов', max_length=255),
        ),
        migrations.AlterField(
            model_name='gym',
            name='coordinates',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gyms.location'),
        ),
        migrations.DeleteModel(
            name='Coordinates',
        ),
    ]
