# Generated by Django 5.0.1 on 2024-01-29 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_location_alter_gym_name_alter_network_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='gym',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gyms.location'),
        ),
    ]
